server {
  listen 80;
  root /usr/share/nginx/html;
  location / { try_files $uri /index.html; }
  location /datasets/ { proxy_pass http://api:8000; }
  location /splits/ { proxy_pass http://api:8000; }
}
